version: '3.7'

services:
  web:
    image: freeboardgames/web:latest
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      SERVER_TYPE: 'WEB'
  bgio:
    image: freeboardgames/gbio:latest
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      SERVER_TYPE: 'BGIO'
  backend:
    image: freeboardgames/backend:latest
    build:
      context: fbg-server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
