version: '3.7'

services:
  fbg:
    container_name: fbg 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - node_modules:/worker/node_modules
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
