domain: my-fbg.info

fbgServer:
  jwtSecret: SECRET_TO_SIGN_JWT

postgresql:
  postgresqlPostgresPassword: PG_ROOT_PASSWORD
  postgresqlUsername: fbgUser
  postgresqlPassword: PG_DB_PASSWORD
  postgresqlDatabase: fbgDb
  service:
    port: 5432

mongodb:
  rootPassword: MONGO_ROOT_PASSWORD
  username: fbgUser
  password: MONGO_DB_PASSWORD
  database: fbgDb
  service:
    port: 27017