domain: www.freeboardgames.org

fbgServer:
  jwtSecret: SECRET_TO_SIGN_JWT

postgresql:
  postgresqlPostgresPassword: PG_ROOT_PASSWORD
  postgresqlUsername: fbgUser
  postgresqlPassword: PG_DB_PASSWORD
  postgresqlDatabase: fbgDb
  service:
    port: 5432